urls.py
from django.urls import path
from .views import IndexView, LeaderboardView, ClanListView, ClanDetailView, ScuffleProfileDetailView, SeasonArchiveIndexView

app_name = "scuffle"

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('clans', ClanListView.as_view(), name='clan_list'),
    path('clan/<int:pk>', ClanDetailView.as_view(), name='clan'),
    path('leaderboard', LeaderboardView.as_view(), name='leaderboard'),
    path('season_history', SeasonArchiveIndexView.as_view(), name='history'),
    path('profile/<str:handle>', ScuffleProfileDetailView.as_view(), name='profile'),

]

models.py
from django.db import models
from nibble.models import NibbleProfile

class Clan(models.Model):
    name = models.CharField(max_length=50)
    icon = models.CharField(max_length=5, default="🏠")
    description = models.TextField()

    def __str__(self):
        return self.name

class ScuffleProfile(models.Model):
    nibbleProfile = models.OneToOneField(NibbleProfile, on_delete=models.CASCADE)
    points = models.IntegerField(default=0)
    clan = models.ForeignKey(Clan, on_delete=models.CASCADE, null=True, blank=True, related_name="people")

    @property
    def points_in_total(self):
        return (self.nibbleProfile.points + self.points)

    def __str__(self):
        return f"@{self.nibbleProfile.handle} ({self.nibbleProfile.user.username})"

class Season(models.Model):
    ordinal = models.IntegerField(unique=True)
    name = models.CharField(max_length=250, unique=True)
    start_date = models.DateField()
    end_date = models.DateField()
    has_finished = models.BooleanField()

    def __str__(self):
        return f"Season {self.ordinal}: {self.name}"

class ClanSeasonRecord(models.Model):
    clan = models.ForeignKey(Clan, on_delete=models.CASCADE, related_name="clan_records")
    season = models.ForeignKey(Season, on_delete=models.CASCADE, related_name="season_records")
    points_total = models.IntegerField()
    rank = models.PositiveIntegerField()
    out_of = models.PositiveIntegerField() # How many clans there were in given season

    def __str__(self):
        return f"{self.clan.name} during season {self.season.ordinal}: {self.rank}/{self.out_of}"

class Activity(models.Model):
    name = models.CharField(max_length=250)
    points = models.IntegerField()
    season = models.ForeignKey(Season, on_delete=models.CASCADE)
    assigned_to = models.ForeignKey(ScuffleProfile, on_delete=models.CASCADE, related_name="activities")

    def __str__(self):
        return f"{self.points} pts for {self.assigned_to.nibbleProfile.user.username}: {self.name}"

views.py
from django.views.generic import TemplateView, ListView, DetailView, ArchiveIndexView
from django.shortcuts import get_object_or_404
from django.db.models import F
from .models import Clan, ScuffleProfile, Season

class IndexView(TemplateView):
    template_name = 'scuffle/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['message'] = 'Hi, welcome to Scuffle module!'
        return context

class ClanListView(ListView):
    # TODO: Most points user + points in total for each clan
    template_name = 'scuffle/clan_list.html'
    model = Clan
    context_object_name = "clans"

class ClanDetailView(DetailView):
    model = Clan
    template_name = 'scuffle/clan.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        clan = self.get_object()
        context['season_records'] = clan.clan_records.all()
        return context

class LeaderboardView(TemplateView):
    template_name = 'scuffle/leaderboard.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        clans = Clan.objects.all()
        context['clans'] = clans

        for clan in context['clans']:
            clan.leaderboard = clan.people.all().annotate(
                total_points = F('points')+F('nibbleProfile__points') #calculate manually since it's not a field but a @property
            ).order_by('-total_points')
        return context

class SeasonArchiveIndexView(ArchiveIndexView):
    model = Season
    date_field = 'end_date'
    template_name = 'scuffle/season_history.html'
    context_object_name = 'seasons'
    allow_future = True

    def get_queryset(self):
        return Season.objects.prefetch_related("season_records__clan")

class ScuffleProfileDetailView(DetailView):
    model = ScuffleProfile
    template_name = 'scuffle/profile.html'
    context_object_name = 'profile'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profile = self.get_object()
        activities = profile.activities.all()
        context["activities"] = activities
        return context

    def get_object(self):
        return get_object_or_404(ScuffleProfile, nibbleProfile__handle=self.kwargs["handle"])

templates/scuffle/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block "title" %}{% endblock %} || Scuffle clans</title>
</head>
<body>
    <nav>
        <a href="{% url 'scuffle:index' %}">Index</a> ||
        <a href="{% url 'scuffle:clan_list' %}">All clans</a> ||
        <a href="{% url 'scuffle:history' %}">History of seasons </a> ||
        <a href="{% url 'scuffle:profile' handle='person1' %}">Examplary profile</a>
    </nav>
    {% block "content" %}{% endblock %}
</body>
</html>

templates/scuffle/clan.html
{% extends "scuffle/base.html" %}
{% block "title" %}Clan {{clan.name}}{% endblock %}
{% block "content" %}

<h1>{{clan.icon}} {{clan.name}} {{clan.icon}}</h1>
<p>{{clan.description}}</p>
<h2>Clan leaderboard:</h2>
<h3>Total points:</h3>
<div>
    List of all people and their points and their profiles
</div>
<h2>Clan history:</h2>
{% for record in season_records %}
<h3>Season {{record.season.ordinal}}: {{record.season.name}} </h3>
<u>Rank:</u> <b>{{record.rank}}</b> out of {{record.out_of}} clans <br/>
<u>Points gathered that season:</u> <b>{{record.points_total}}</b>
<!-- It could be shown like those circles with "300 happy customers!" and other stats in pretty circles-->
{% endfor %}
<h2>Clan activity:</h2>
logs of the last few stuff, load every 5 or 10 items; mostly from Nibble, I guess

{% endblock %}

templates/scuffle/clan_list.html
{% extends "scuffle/base.html" %}
{% block "title" %}List of clans{% endblock %}
{% block "content" %}

<h1>All clans</h1>
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias veniam sapiente eveniet possimus, similique corporis voluptatibus ab, porro sit architecto natus sed repellendus laborum beatae, quas et? Nam, nostrum ducimus. Something witty or something. </p>
<p>Something cool about the rivalry within the mischief that we're working together but a bit of scuffle for ~~cheese~~ points is always cool.</p>

{% for clan in clans %}
    <div style="text-align: center;">

        <h2>
            <a href="{% url 'scuffle:clan' pk=clan.id %}">
                {{clan.icon}} {{clan.name}} {{clan.icon}}
            </a>
        </h2>
        <p> {{clan.description}} </p>

        <div>
            <h3>Points total:</h3>
        </div>

        <div>
            <h3>The most points in the clan:</h3>
        </div>

        <hr>
        
    </div>
{% endfor %}

{% endblock %}

templates/scuffle/index.html
{% extends "scuffle/base.html" %}
{% block "title" %}Welcome!{% endblock %}
{% block "content" %}
{{message}}! :&gt;
{% endblock %}

templates/scuffle/leaderboard.html
{% extends "scuffle/base.html" %}
{% block "title" %}Leaderboard{% endblock %}
{% block "content" %}

{% for clan in clans %}
    <h1>{{clan.icon}} {{clan.name}} {{clan.icon}}</h1>
    {% for person in clan.leaderboard %}
    <div>
        @{{person.nibbleProfile.handle}} - 
        {{person.points}} + {{person.nibbleProfile.points}} = {{person.points_in_total}}
    </div>
    {% endfor %}
{% endfor %}

{% endblock %}

templates/scuffle/profile.html
{% extends "scuffle/base.html" %}
{% block "title" %}{{profile.nibbleProfile.user.username}}'s Profile{% endblock %}
{% block "content" %}

<h1>{{profile.nibbleProfile.avatar}} {{profile.nibbleProfile.user.username}}</h1>
<h2 style="font-style: italic;">@{{profile.nibbleProfile.handle}}</h2>
<h3>Points total: {{profile.points_in_total}}</h3>
<b>From Nibble:</b> {{profile.nibbleProfile.points}}
<br />
<b>From Scuffle:</b> {{profile.points}}
<br/><br/>
{% for activity in activities %}
<b>{{activity.name}}</b>: {{activity.points}} <br/>
{% endfor %}
<br/>
nibbleProfile: <a href="{% url 'nibble:profile' handle=profile.nibbleProfile.handle %}">
    Go to this person's profile on Nibble!
</a>

{% endblock %}

templates/scuffle/season_history.html
{% extends "scuffle/base.html" %}
{% block "title" %}Season Archive{% endblock %}
{% block "content" %}

{% for season in seasons %}
<h1>Season #{{season.ordinal}}: <i>{{season.name}}</i></h1>
<b>Started on</b> {{season.start_date}}, <b>ended on</b> {{season.end_date}} <br/>
{% for record in season.season_records.all %}
{{record}} <br/>
{% endfor %}
{% endfor %}

{% endblock %}